# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ruby_getting_started_development
  username: ruby_getting_started
  password: hello123

test:
  <<: *default
  database: ruby_getting_started_test
  username: ruby_getting_started
  password: hello123

production:
  <<: *default
  database: ruby_getting_started_production
  username: ruby_getting_started
  password: <%= ENV['RUBY_GETTING_STARTED_DATABASE_PASSWORD'] %>
